### ISSUE TITLE
Intermitent errors: Loading - undefined

### ISSUE THREAD

**Issue by evroom** [KristjanESPERANTO/MMM-PublicTransportHafas#185] opened 2024-12-08 15:09 UTC
Hi,

since the last couple of weeks I am getting these intermittent errors, where the module shows "Loading - undefined"

I do not know if it is the module, the hafas-client or the endpoint (Deutsche Bahn).

MM details:
```
$ grep version ~/MagicMirror/package.json
	"version": "2.30.0",
$ npm -v
10.9.2
$ node -v
v20.18.1
$ uname -a
Linux BlackPi4b 6.6.62+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

This is the common sequence.

pm2 log:
```
$ pm2 logs MagicMirror --lines 100
:
:
0|MagicMirror  | [2024-12-08 15:52:03.995] [LOG]   [MMM-PublicTransportHafas.js:228:15] TransportHafas update OK, station : Nürnberg-Rehhof at : NaN
0|MagicMirror  | [2024-12-08 15:52:04.022] [LOG]   [MMM-PublicTransportHafas.js:228:15] TransportHafas update OK, station : Nürnberg-Rehhof at : NaN
0|MagicMirror  | [2024-12-08 15:52:31.285] [ERROR] [MMM-PublicTransportHafas.js:143:11] null
0|MagicMirror  | [2024-12-08 15:52:31.301] [ERROR] [MMM-PublicTransportHafas.js:143:11] null
0|MagicMirror  | [2024-12-08 15:53:03.587] [LOG]   [
0|MagicMirror  |   {
0|MagicMirror  |     tripId: '2|#VN#1#ST#1733178662#PI#0#ZI#392829#TA#2#DA#81224#1S#8002612#1T#1533#LS#8005185#LT#1650#PU#80#RT#1#CA#s#ZE#2#ZB#S      2#PC#4#FR#8002612#FT#1533#TO#8005185#TT#1650#',
:
:
```

This I also caught.

pm2 log:
```
$ pm2 logs MagicMirror --lines 100
:
:
0|MagicMirror  | [2024-12-08 15:43:17.619] [LOG]   [MMM-PublicTransportHafas.js:228:15] TransportHafas update OK, station : Nürnberg-Rehhof at : NaN
0|MagicMirror  | [2024-12-08 15:43:17.628] [LOG]   [MMM-PublicTransportHafas.js:228:15] TransportHafas update OK, station : Nürnberg-Rehhof at : NaN
0|MagicMirror  | [2024-12-08 15:44:12.194] [ERROR] (node:1144) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
0|MagicMirror  |     at TCP.get [as reading] (node:_tls_wrap:748:10)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:76)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/admin/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  | [2024-12-08 15:44:12.195] [ERROR] (node:1144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
0|MagicMirror  | [2024-12-08 15:44:12.805] [ERROR] [MMM-PublicTransportHafas.js:143:11] null
0|MagicMirror  | [2024-12-08 15:44:12.813] [ERROR] [MMM-PublicTransportHafas.js:143:11] null
```

**Comment by evroom** [comment] 2024-12-08 15:55
I just was able to take a picture of this:
```
Loading - request to https://reiseauskunft.bahn.de/bin/mgate.exe....
checksum=785a0195ed91421c0d8f657fe0f.....
failed, reason: socket hang up
```
Cannot find this in the error log(s).

So this example is a hafas-client endpoint issue.

**Comment by KristjanESPERANTO** [comment] 2024-12-10 22:47
I can't reproduce this. Can you show me your config of the module? :slightly_smiling_face:

**Comment by evroom** [comment] 2024-12-11 07:52
Here there config:

```
  {
    module: "MMM-PublicTransportHafas",
    disabled: false,
    position: "top_right",
    header: "DEPARTURES",
    config: {
      stationID: "8004491",
      stationName: "Nürnberg-Rehhof",
      updatesEvery: 60,
      timeInFuture: 180,
      direction: "",
      ignoredLines: [],
      excludedTransportationTypes: ["bus"],
      timeToStation: 5,
      displayLastUpdate: true,
      displayLastUpdateFormat: "dddd MMM D - HH:mm",
      showColoredLineSymbols: true,
      useColorForRealtimeInfo: true,
      noRealtimeDelayString: "⚠",
      showTableHeadersAsSymbols: true,
      maxUnreachableDepartures: 2,
      maxReachableDepartures: 10,
      customLineStyles: "nuernberg",
      showOnlyLineNumbers: true
    }
  },
```
Unfortunately it is not something you can reproduce at will.
For some period it is stable, then there is a period with several ```"Loading - undefined"```occurrences.

**Comment by KristjanESPERANTO** [comment] 2024-12-12 00:15
There doesn't seem to be another endpoint that you could use for testing. This makes it difficult to narrow it down 🤔

**Comment by evroom** [comment] 2024-12-12 08:00
You can remove the bug status, if possible (no idea how to do that).

You will see more info in the log with MMM-LogExt installed.
I have that on another MM install.
On my 'production' Pi I have this not installed, as I think it is too weak, but I can give it a go later on.

So, I have the module now running on 2 Raspberry Pis (Raspberry Pi 3 Model B Plus & Raspberry Pi 4 Model B), let's see.

PS: I see now that this is printed in the error log (on the Pi 4):

/home/admin/.pm2/logs/MagicMirror-error.log:[2024-12-12 08:45:44.764] [ERROR] [MMM-PublicTransportHafas.js:143:11] null

I do not see it on the Pi 3, but the "Loading - undefined" does occur there too.

**Comment by Rene1695** [comment] 2024-12-13 17:49
Hi I have exactly the same issue as @evroom 

![image](https://github.com/user-attachments/assets/15d501ad-3bbf-4e11-b56d-13bc0eb28e97)

It is stable for like 10-15 minutes and then I get this error message for like 2-3 minutes and then repeat. 

My config looks like this: 

'''
{
			module: "MMM-PublicTransportHafas",
			position: "bottom_left",
		  
			config: {
			  // Departures options
			  stationID: "MyID",                   
			  stationName: "MyName", 
			  direction: "",                   
			  excludedTransportationTypes: [],  
			  ignoredLines: ["Bus 55"],                 
			  timeToStation: 6,              
			  updatesEvery: 120,
			  timeInFuture: 90,
			  tableHeaderOrder: [ "time", "line", "direction" ],
		  
			  // Look and Feel
			  displayLastUpdate: true,          
			  maxUnreachableDepartures: 0,      
			  maxReachableDepartures: 4,        
			  showColoredLineSymbols: true,     
			  customLineStyles: "",          
			  showOnlyLineNumbers: false,       
			  showTableHeadersAsSymbols: true,  
			  useColorForRealtimeInfo: true,    
			  displayLastUpdateFormat: "HH:mm:ss"
			}
		  },
'''

**Comment by evroom** [comment] 2024-12-13 21:49
I will try to change to another profile and give it a try.
Have been using db and I suspect that they cannot handle the amount of requests at certain times.
My local transport network is not listed in the list and I guess that they rely on the DB information too.

**Comment by evroom** [comment] 2024-12-13 21:55
I only now read that there is also a profile named db-hafas.
“Consider using [db-hafas](https://github.com/derhuerst/db-hafas#db-hafas), to always get the customized client right away.”
Worth a try.

**Comment by Rene1695** [comment] 2024-12-14 07:26
I tried `db` , `db-hafas`  and `vbn` which is my regional ÖPNV but I didn't see any difference with that profiles. Still the same issue, at least for me

**Comment by KristjanESPERANTO** [comment] 2024-12-14 18:04
I have adjusted the logging slightly to track down the error :bug: Please update the module and report the error message that is then displayed.

**Comment by Rene1695** [comment] 2024-12-14 19:22
Pulled, here's the output:

![image](https://github.com/user-attachments/assets/b871b751-fec2-4b92-8735-dcc8302b5a9d)

**Comment by evroom** [comment] 2024-12-15 15:11
@KristjanESPERANTO 
Thanks for the update logging.

This is what I caught so far:
```
admin@MagicPi3:~ $ date; grep 'MMM-PublicTransportHafas' /home/admin/.pm2/logs/MagicMirror-*.log | grep "ERROR"
Sun 15 Dec 16:06:26 CET 2024
/home/admin/.pm2/logs/MagicMirror-error.log:[15.12.2024 12:43.10.393] [ERROR] [MMM-PublicTransportHafas.js:143:11] request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=08dd154b0eea513ebb8e91fbfd3c26e7 failed, reason: socket hang up
/home/admin/.pm2/logs/MagicMirror-error.log:[15.12.2024 13:29.10.302] [ERROR] [MMM-PublicTransportHafas.js:143:11] request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=7c2d9ea59c388b419b6660a7ee45dc50 failed, reason: socket hang up
/home/admin/.pm2/logs/MagicMirror-error.log:[15.12.2024 14:15.09.732] [ERROR] [MMM-PublicTransportHafas.js:143:11] request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=163dfc687ef8c36424b888e6c4e972ec failed, reason: socket hang up
/home/admin/.pm2/logs/MagicMirror-error.log:[15.12.2024 15:06.13.667] [ERROR] [MMM-PublicTransportHafas.js:143:11] request to https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=25aa67aae51a0651ceb5dd8d97beffc3 failed, reason: socket hang up
```

**Comment by evroom** [comment] 2024-12-16 09:46
So it means that when the first error occurs, the display will keep showing the list from the last successful request ?
Do not know exactly how to describe it, hope you understand.
Then when the 2nd error occurs, the error is being showed on the display, right ?

I have pulled your change, observing now.

In the meantime, perhaps a suggestion:

You have this option "displayLastUpdate: true" and with that you can potentially play a bit.

"Last update: Mon 16 Dec 10:35:37 CET 2024" (show when last request was okay - socketIssueCount = 0)
"Last update (socket issues: 2): Mon 16 Dec 10:35:37 CET 2024"  (show when socketIssueCount > 0)

In any case, always show the last successful request.

You can also opt to show the error when for example socketIssueCount > 10.

Just brainstorming a bit.

**Comment by evroom** [comment] 2024-12-16 14:13
Just a small remark.
Do not know if this was introduced recently, or that is was present like this previously:

```
/home/admin/.pm2/logs/MagicMirror-out.log:[16.12.2024 15:04.16.920] [DEBUG] [MMM-PublicTransportHafas] [
/home/admin/.pm2/logs/MagicMirror-out.log:[16.12.2024 15:04.16.948] [LOG]   [MMM-PublicTransportHafas.js:242:15] [MMM-PublicTransportHafas] Update OK, station : Nürnberg-Rehhof at : NaN
```
The DEBUG info is not present.

**Comment by KristjanESPERANTO** [comment] 2024-12-16 20:07
> The DEBUG info is not present.

It is present in the following lines of the log, but grep only got the first one.

> So it means that when the first error occurs, the display will keep showing the list from the last successful request ?

Yes.

> Then when the 2nd error occurs, the error is being showed on the display, right ?

Only if the second error occurs right after the first. The error counter is reset by a successful request. So if there is only one error per hour, no one would notice.

> You can also opt to show the error ...

That's a good idea. I might include that sometime. A PR would also be welcome :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment] 2024-12-28 12:25
I'm closing this issue as the reported problem has been handled. Eventually we will follow the fine tuning suggested in issue #186 :slightly_smiling_face:

**Closed by KristjanESPERANTO** 2024-12-28 12:25 UTC
Labels: bug

**Comment by drtorchwood** [comment] 2025-01-09 22:48
Hi, 

since a few days I don't receive any data. I updated the module and MagicMirror to the latest version and it's still not working. 
When I run `npm run query`, I'm asked to enter a station name and then I end up with this error:

```
Error: Service Temporarily Unavailable
    at Object.request (file:///home/pi/MagicMirror/modules/MMM-PublicTransportHafas/node_modules/hafas-client/lib/request.js:189:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.locations (file:///home/pi/MagicMirror/modules/MMM-PublicTransportHafas/node_modules/hafas-client/index.js:466:25)
    at async file:///home/pi/MagicMirror/modules/MMM-PublicTransportHafas/convenience/query_stations.mjs:71:28 {
  request: Request {
    size: 0,
    timeout: 0,
    follow: 20,
    compress: true,
    counter: 0,
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype],
      keepAliveMsecs: 1000,
      keepAlive: true,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false
    },
    [Symbol(Body internals)]: {
      body: <Buffer 7b 22 6c 61 6e 67 22 3a 22 65 6e 22 2c 22 73 76 63 52 65 71 4c 22 3a 5b 7b 22 63 66 67 22 3a 7b 22 70 6f 6c 79 45 6e 63 22 3a 22 47 50 41 22 2c 22 72 ... 271 more bytes>,
      disturbed: false,
      error: null
    },
    [Symbol(Request internals)]: {
      method: 'POST',
      redirect: 'follow',
      headers: [Headers],
      parsedURL: [Url],
      signal: null
    }
  },
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: false, error: null },
    [Symbol(Response internals)]: {
      url: 'https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=ce2b3c14b4e4f3130976f1367a54e5cd',
      status: 503,
      statusText: 'Service Temporarily Unavailable',
      headers: [Headers],
      counter: 0
    }
  },
  url: 'https://reiseauskunft.bahn.de/bin/mgate.exe?checksum=ce2b3c14b4e4f3130976f1367a54e5cd'
}
```

In the log of MagicMirror, I find these error lines:

```
0|MagicMirror  | [2025-01-09 23:45:02.415] [ERROR] (node:1144) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
0|MagicMirror  |     at SecureContext.hasOwnProperty (<anonymous>)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:45)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  |     at hasBinary (/home/pi/MagicMirror/node_modules/socket.io-parser/build/cjs/is-binary.js:49:63)
0|MagicMirror  | [2025-01-09 23:45:02.418] [ERROR] (node:1144) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 104)
```

If I use `npm run query rmv` it works.

**Comment by evroom** [comment] 2025-01-10 07:43
I see the exact same thing.
The code could perhaps handle this exception a bit nicer, but the real culprit is DB.

https://reiseauskunft.bahn.de
503 Service Temporarily Unavailable

Searching via https://www.bahn.de/buchung/fahrplan/suche is working tough, so perhaps there is a new URL to use ?

**Comment by drtorchwood** [comment] 2025-01-10 10:39
Seems like the old Hafas API is not working anymore. 
https://www.ice-treff.de/index.php?id=709439
https://www.drehscheibe-online.de/foren/read.php?003,11015839,11015839#msg-11015839

Perhaps, one should a warning to the readme file and ask users to set a profile explicitly instead of using `db` by default.

**Comment by evroom** [comment] 2025-01-10 16:47
@Rene1695 

See https://forum.magicmirror.builders/topic/19315/mmm-publictransporthafas-service-temporarily-unavailable
for some comments.
I personally would continue the discussion there, as this issue is in fact closed and the issue is not really related to the code itself, but to the provider of the data.
I got it running again, with a restriction, and used the profile oebb, but it greatly depends on your location and the means of public transport.
